site_name: Deepest Documentation
theme: readthedocs
docs_dir: docs
repo_url: http://github.com/deepest2017/deepestdocs
site_url: http://deepestdocs.readthedocs.io

markdown_extensions:
    - mdx_math
    - fenced_code

extra_javascript: 
    - http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

pages:
    - Home: index.md
    - Teaching:
        - 000 Machine Learning:
            - 0000 Machine Learning Basic: teaching/000_machine_learning/0000_machine_learning_basic.md
            - 0001 Machine Learning Advanced: teaching/000_machine_learning/0001_machine_learning_advanced.md
            - 0002 Machine Learning Master: teaching/000_machine_learning/0002_machine_learning_master.md
        - 001 Tensorflow:
            - 0010 Tensorflow Basic: teaching/001_tensorflow/0010_tensorflow_basic.md
            - 0011 Tensorflow Advanced: teaching/001_tensorflow/0011_tensorflow_advanced.md
            - 0012 Tensorflow Master: teaching/001_tensorflow/0012_tensorflow_master.md