site_name: Deepest Documentation
theme: readthedocs
docs_dir: docs
repo_url: http://github.com/deepest2017/deepestdocs
site_url: http://deepestdocs.readthedocs.io

markdown_extensions:
    - mdx_math

extra_javascript: 
    - http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

pages:
    - Home: index.md
    - Teaching:
        - 000 Introduction:
            - 0000 Introduction Start: teaching/000_introduction/index.md
        - 001 Tensorflow:
            - 0010 Tensorflow Basic: teaching/001_tensorflow/0010_tensorflow_basic/0010_tensorflow_basic.md
            - 0011 Tensorflow Advanced: teaching/001_tensorflow/0011_tensorflow_advanced/index.md