site_name: Deepest Documentation
theme: readthedocs
docs_dir: docs
repo_url: http://github.com/deepest2017/deepestdocs
site_url: http://deepestdocs.readthedocs.io

markdown_extensions:
    - mdx_math
    - fenced_code

extra_javascript: 
    - http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

pages:
    - Home: index.md
    - Overview: overview.md
    - 000 Machine Learning:
        - 0000 Machine Learning Basic: 000_machine_learning/0000_machine_learning_basic.md
        - 0001 Machine Learning Advanced: 000_machine_learning/0001_machine_learning_advanced.md
        - 0002 Machine Learning Master: 000_machine_learning/0002_machine_learning_master.md
    - 001 Tensorflow:
        - 0010 Tensorflow Basic: 001_tensorflow/0010.md
        - 0011 Tensorflow Advanced: 001_tensorflow/0011.md
        - 0012 Tensorflow Master: 001_tensorflow/0012.md
    - 002 Deep Learning (DL) Part 1:
        - 0020 DL Terms & Concepts: 002_deep_learning_part_1/0020.md
        - 0021 Gradient Descent & Momentum: 002_deep_learning_part_1/0021.md
        - 0022 Back Propagation: 002_deep_learning_part_1/0022.md
        - 0023 Loss & Metric: 002_deep_learning_part_1/0023.md
        - 0024 Activation Function: 002_deep_learning_part_1/0024.md
        - 0025 Initialization: 002_deep_learning_part_1/0025.md
    - 004 Deep Learning (DL) Part 2:
        - 0040 Multi-Layer Perceptron (MLP): 004_deep_learning_part_2/0040.md
        - 0041 Weight Decay: 004_deep_learning_part_2/0041.md
        - 0042 Dropout: 004_deep_learning_part_2/0042.md
        - 0043 Convolutional Neural Network (CNN): 004_deep_learning_part_2/0043.md
        - 0044 Adaptive Learning Rate: 004_deep_learning_part_2/0044.md
        - 0045 Batch Normalization (BN): 004_deep_learning_part_2/0045.md
        - 0046 Recurrent Neural Network (RNN): 004_deep_learning_part_2/0046.md